### ISSUE TITLE
Installing Background

### ISSUE THREAD

**Issue by vanshreee** [EnricoCorsaro/Background#1]
Hello, I am trying to install Background in the same directory that contains Diamonds. I have successfully installed Diamonds and PeakBagging, and am not sure why the same method doesn't work for Background. 
After using Sourcetree to clone Backgrounds into the same directory ~ as Diamonds, I ran the following commands: 
$ mkdir build
$ cd build
$ cmake ..
$ make -j 4

The first 3 commands worked well bit after I ran make -j 4, I got: 
~/Diamonds/include/Eigen/Core:247:10: fatal error: 
      'omp.h' file not found

Not sure if I have done something wrong, or if there is a bug? P.S. I have CMake installed and my Mac is 10.6 and greater.

**Comment by EnricoCorsaro** [comment]
Dear Vnashree,

sorry for my late reply. You are right about this, and this issue was actually solved. There was a wrong statement in the CMakeLists.txt file, which is now correct. I do simply recommend redownloading the entire package and reinstalling it following the usual steps.
Does this solve your problem?

Best,
Enrico

**Comment by vanshreee** [comment]
Hi Enrico,
Thank you ! You actually emailed me back about this some time ago and all
your suggestions worked well. Thank you for replying to the GitHub issue as
well. Best regards

**Comment by EnricoCorsaro** [comment]
OK excellent! Thanks for your input.
Best,
Enrico
